baseURL = 'https://devlog.uhstray.io/'
languageCode = 'en-us'
title = 'Uhstray'
author = ["Joe Wisneski", "Jacob Haig"]

copyright = "Â© [Uhstray.io](https://uhstray.io)"

DefaultContentLanguage = "en"
enableInlineShortcodes = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
ignoreErrors = ["error-remote-getjson"]

[module]
[[module.imports]]
path = 'github.com/joeroe/risotto'


[pagination]
pagerSize = 3 # This is the number of items to display per page

[params]
noindex = false # This is for search engines, set to true to disable indexing

[params.theme]
palette = "tokyo-night-dark"


# Sidebar: social links
[params.about]
title = "Uhstray.io devlog"
description = "Check out [Uhstray.io](https://www.uhstray.io/)'s blog and devlog for our latest updates."
# unicode/emoji logo:
logo = "ðŸ“"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/uhstray-io/"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:uhstray@uhstray.io"

[[params.socialLinks]]
icon = "ai ai-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0001-2345-6789"


[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "Blogs"
name = "Blogs"
url = "/blogs/"
weight = 10

[[menu.main]]
identifier = "Dev logs"
name = "Dev logs"
url = "/devlogs/"
weight = 10



# Taxonomies are like categories and tags. They help to classify content.
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

# Table of contents
# Add toc = true to content front matter to enable
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

[privacy]

# [privacy.vimeo]
# disabled = false
# simple = true

# [privacy.twitter]
# disabled = false
# enableDNT = true
# simple = true

# [privacy.instagram]
# disabled = false
# simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

# [services.twitter]
# disableInlineCSS = true


timeout = 30000
enableInlineShortcodes = true

